"""second migrate

Revision ID: 960df8c5b602
Revises: 
Create Date: 2020-02-16 08:54:23.550885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960df8c5b602'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('date_commented', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('posts_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'posts', ['posts_id'], ['id'])
    op.drop_column('comments', 'post_id')
    op.drop_column('comments', 'date_posted')
    op.add_column('posts', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('date_registered', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_registered')
    op.drop_column('posts', 'views')
    op.add_column('comments', sa.Column('date_posted', sa.DATETIME(), nullable=True))
    op.add_column('comments', sa.Column('post_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'status')
    op.drop_column('comments', 'posts_id')
    op.drop_column('comments', 'date_commented')
    # ### end Alembic commands ###
